apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: arunhari82 # This must match with your github account name
spec:
  profile:
    displayName: Arun Hariharan # Can be any arbitrary value, will default to metadata.name value if not inserted.
  memberOf: []
